apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: phpmyadmin-claim0
  name: phpmyadmin-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
