apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/php81fpmwordpressmysql830-wp-net: "true"
        io.kompose.service: wordpress
    spec:
      containers:
        - env:
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                /* wpconfig */
                define( 'FS_METHOD', 'direct' );
            - name: WORDPRESS_DB_HOST
              value: database
            - name: WORDPRESS_DB_NAME
              value: wordpress-db
            - name: WORDPRESS_DB_PASSWORD
              value: changeme
            - name: WORDPRESS_DB_USER
              value: wp-user
            - name: WORDPRESS_DEBUG
              value: "1"
          image: wordpress:latest
          name: wordpress
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress
      restartPolicy: Always
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: wordpress
